#!/usr/bin/env python3
"""
Industrial PPE Retraining Dataset Collector
==========================================
Captures clean, unannotated video frames from CCTV cameras and pairs them with
standard YOLO format annotation files (.txt) generated by the deep learning model.

Key Features:
- Saves raw unannotated frames (NO bounding boxes baked into image pixels) for retraining.
- Generates standard normalized YOLO annotation files: <class_id> <x_center> <y_center> <width> <height>.
- Automatically creates `data.yaml` and `classes.txt` for 100% plug-and-play training or Label Studio/CVAT editing.
- Uploads dataset directly to S3 (`retraining_dataset/images/` and `retraining_dataset/labels/`) with local backup.
- Configurable collection duration (e.g. `--days 3` or `--hours 72`) and sampling rate.
- Focuses on frames with detections (including lower-confidence hard examples) to capture false positives for retraining.
"""

from concurrent.futures import ThreadPoolExecutor
from collections import defaultdict
from pathlib import Path
from datetime import datetime, timedelta
import os
os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"] = "rtsp_transport;tcp|stimeout;5000000|buffer_size;1024000"

import argparse
import json
import random
import threading
import time

import boto3
import cv2
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
from dotenv import load_dotenv
import numpy as np
import torch
from ultralytics import YOLO

# Load environment configuration
load_dotenv()

# Configure OpenCV RTSP capture options
os.environ["OPENCV_FFMPEG_CAPTURE_OPTIONS"] = "rtsp_transport;tcp|stimeout;5000000|buffer_size;1024000"

dir_path = os.path.dirname(os.path.realpath(__file__))

# Model path resolution
DEFAULT_MODEL_PATH = os.getenv("MODEL_PATH", "model/best12classes.pt")

# 12 Classes configuration matching best12classes.pt
YAML_CLASS_NAMES = {
    0: 'Gloves',
    1: 'Goggles',
    2: 'Helmet',
    3: 'Mask',
    4: 'No Gloves',
    5: 'No Goggles',
    6: 'No Helmet',
    7: 'No Mask',
    8: 'No Shoes',
    9: 'No Suit',
    10: 'Shoes',
    11: 'Suit'
}

# S3 configuration
bucket_name = os.getenv('BUCKET_NAME')
s3_endpoint_url = os.getenv('S3_ENDPOINT_URL')
aws_access_key_id = os.getenv('AWS_ACCESS_KEY_ID')
aws_secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY')

s3 = None
try:
    if s3_endpoint_url and aws_access_key_id and aws_secret_access_key:
        s3 = boto3.client(
            's3',
            endpoint_url=s3_endpoint_url,
            aws_access_key_id=aws_access_key_id,
            aws_secret_access_key=aws_secret_access_key,
            verify=False
        )
except Exception as e:
    print(f"S3 client initialization note: {e}")


def resolve_model_path(specified_path=None):
    """Resolves YOLO model weights path cross-platform."""
    candidates = []
    if specified_path:
        candidates.append(Path(specified_path))
    if os.getenv("MODEL_PATH"):
        candidates.append(Path(os.getenv("MODEL_PATH")))

    candidates.extend([
        Path(dir_path) / "model" / "best12classes.pt",
        Path("model/best12classes.pt"),
        Path("PPEsDetection/model/best12classes.pt"),
        Path(dir_path) / "best12classes.pt",
        Path(dir_path) / "model" / "best.pt",
        Path("model/best.pt"),
    ])

    for candidate in candidates:
        if candidate and candidate.exists():
            return str(candidate.resolve())

    return specified_path or str(Path(dir_path) / "model" / "best12classes.pt")


def convert_to_yolo_bbox(xyxy, img_w, img_h):
    """
    Converts absolute pixel coordinates [x1, y1, x2, y2] to standard YOLO format:
    normalized [x_center, y_center, width, height] bounded to [0.0, 1.0].
    """
    x1, y1, x2, y2 = xyxy
    x1 = max(0.0, min(float(x1), float(img_w)))
    y1 = max(0.0, min(float(y1), float(img_h)))
    x2 = max(0.0, min(float(x2), float(img_w)))
    y2 = max(0.0, min(float(y2), float(img_h)))

    box_w = x2 - x1
    box_h = y2 - y1
    cx = x1 + (box_w / 2.0)
    cy = y1 + (box_h / 2.0)

    # Normalize by frame dimensions and format to 6 decimals
    norm_cx = round(cx / float(img_w), 6)
    norm_cy = round(cy / float(img_h), 6)
    norm_w = round(box_w / float(img_w), 6)
    norm_h = round(box_h / float(img_h), 6)

    return norm_cx, norm_cy, norm_w, norm_h


def create_dataset_structure(base_dir, s3_prefix="retraining_dataset"):
    """
    Sets up local folder structure and generates `data.yaml` and `classes.txt`.
    Also uploads the dataset configuration files to S3.
    """
    local_base = Path(base_dir)
    images_dir = local_base / "images"
    labels_dir = local_base / "labels"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    # 1. Create data.yaml
    yaml_lines = [
        f"path: {local_base.resolve()}",
        "train: images",
        "val: images",
        "",
        f"nc: {len(YAML_CLASS_NAMES)}",
        "names:"
    ]
    for cid in sorted(YAML_CLASS_NAMES.keys()):
        yaml_lines.append(f"  {cid}: '{YAML_CLASS_NAMES[cid]}'")

    yaml_content = "\n".join(yaml_lines) + "\n"
    yaml_file = local_base / "data.yaml"
    with open(yaml_file, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    # 2. Create classes.txt (for Roboflow / Label Studio / CVAT)
    classes_content = "\n".join([YAML_CLASS_NAMES[cid] for cid in sorted(YAML_CLASS_NAMES.keys())]) + "\n"
    classes_file = local_base / "classes.txt"
    with open(classes_file, "w", encoding="utf-8") as f:
        f.write(classes_content)

    # 3. Upload dataset configs to S3 if configured
    if s3 and bucket_name:
        try:
            s3.put_object(Bucket=bucket_name, Key=f"{s3_prefix}/data.yaml", Body=yaml_content.encode("utf-8"))
            s3.put_object(Bucket=bucket_name, Key=f"{s3_prefix}/classes.txt", Body=classes_content.encode("utf-8"))
            print(f"Uploaded data.yaml and classes.txt to S3: s3://{bucket_name}/{s3_prefix}/")
        except Exception as e:
            print(f"S3 config upload note: {e}")

    return images_dir, labels_dir


class DatasetCollector:
    """
    Multi-threaded CCTV stream collector that samples unannotated frames and
    generates matching YOLO annotation text files for model fine-tuning.
    """

    def __init__(self, model_path, output_dir, s3_prefix="retraining_dataset",
                 sample_interval=45.0, min_conf=0.35, max_conf=0.98, save_empty_ratio=0.03):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"Initializing DatasetCollector on: {self.device}")

        chosen_path = resolve_model_path(model_path)
        print(f"Loading YOLO model weights: {chosen_path}")
        self.model = YOLO(chosen_path).to(self.device)

        if hasattr(self.model, "names") and isinstance(self.model.names, dict) and len(self.model.names) > 0:
            self.model_names = self.model.names
        else:
            self.model_names = YAML_CLASS_NAMES

        self.model_lock = threading.Lock()
        self.output_dir = output_dir
        self.s3_prefix = s3_prefix
        self.sample_interval = sample_interval
        self.min_conf = min_conf
        self.max_conf = max_conf
        self.save_empty_ratio = save_empty_ratio

        self.images_dir, self.labels_dir = create_dataset_structure(self.output_dir, self.s3_prefix)

        self.running = True
        self.stats_lock = threading.Lock()
        self.total_saved = 0
        self.class_counts = defaultdict(int)

    def save_sample(self, raw_frame, yolo_annotations, production_house, area_type):
        """
        Saves a clean raw image and matching YOLO label .txt file locally and to S3.
        """
        now = datetime.now()
        timestamp = now.strftime("%Y%m%d_%H%M%S_%f")[:19]
        safe_ph = production_house.replace(" ", "_").replace("-", "_")
        safe_area = area_type.replace(" ", "_").replace("-", "_")
        file_id = f"{timestamp}_{safe_ph}_{safe_area}"

        # 1. Encode raw JPEG image
        success, img_encoded = cv2.imencode(".jpg", raw_frame, [int(cv2.IMWRITE_JPEG_QUALITY), 95])
        if not success:
            return

        img_bytes = img_encoded.tobytes()

        # 2. Format YOLO label lines: <class_id> <x_center> <y_center> <width> <height>
        label_lines = [
            f"{ann['cid']} {ann['cx']} {ann['cy']} {ann['w']} {ann['h']}"
            for ann in yolo_annotations
        ]
        label_text = "\n".join(label_lines) + ("\n" if label_lines else "")
        label_bytes = label_text.encode("utf-8")

        # 3. Save locally
        local_img_path = self.images_dir / f"{file_id}.jpg"
        local_lbl_path = self.labels_dir / f"{file_id}.txt"

        with open(local_img_path, "wb") as f:
            f.write(img_bytes)

        with open(local_lbl_path, "wb") as f:
            f.write(label_bytes)

        # 4. Upload to S3
        if s3 and bucket_name:
            try:
                s3.put_object(
                    Bucket=bucket_name,
                    Key=f"{self.s3_prefix}/images/{file_id}.jpg",
                    Body=img_bytes
                )
                s3.put_object(
                    Bucket=bucket_name,
                    Key=f"{self.s3_prefix}/labels/{file_id}.txt",
                    Body=label_bytes
                )
            except Exception as e:
                print(f"S3 upload error for {file_id}: {e}")

        # 5. Update stats
        with self.stats_lock:
            self.total_saved += 1
            for ann in yolo_annotations:
                self.class_counts[ann['class_name']] += 1
            current_total = self.total_saved

        classes_found = [ann['class_name'] for ann in yolo_annotations]
        class_summary = ", ".join(classes_found) if classes_found else "Background Sample"
        print(f"[{current_total}] Saved dataset sample: {file_id}.jpg | Objects: [{class_summary}]")

    def process_camera(self, stream_data, plant, production_house, area_type, ppe_list):
        """Worker loop for a single camera feed."""
        # Stagger camera startup across 0.5-25 seconds
        time.sleep(random.uniform(0.5, 25.0))

        stream_link = stream_data.get('streamLink', '')
        if not stream_link:
            return

        try:
            cap = cv2.VideoCapture(stream_link, cv2.CAP_FFMPEG)
        except Exception as e:
            print(f"Error opening camera {stream_link}: {e}")
            return

        last_sample_time = 0.0

        try:
            while self.running:
                now = time.time()
                if now - last_sample_time < self.sample_interval:
                    time.sleep(min(1.0, self.sample_interval - (now - last_sample_time)))
                    continue

                if not cap.isOpened():
                    cap.release()
                    time.sleep(5)
                    cap = cv2.VideoCapture(stream_link, cv2.CAP_FFMPEG)
                    if not cap.isOpened():
                        time.sleep(5)
                        continue

                # Flush buffered frames to get a fresh frame
                for _ in range(2):
                    cap.grab()

                ret, frame = cap.read()
                if not ret or frame is None:
                    cap.release()
                    time.sleep(5)
                    cap = cv2.VideoCapture(stream_link, cv2.CAP_FFMPEG)
                    continue

                last_sample_time = time.time()

                # Resize to standard Full HD 1920x1080 resolution
                frame_1080p = cv2.resize(frame, (1920, 1080))
                h_img, w_img = frame_1080p.shape[:2]

                # Run inference with model_lock to avoid CUDA thread collisions
                with self.model_lock:
                    predictions = self.model.predict(
                        frame_1080p,
                        conf=self.min_conf,
                        verbose=False
                    )

                yolo_annotations = []

                for result in predictions:
                    boxes = result.boxes
                    if boxes is None or len(boxes) == 0:
                        continue

                    xyxy = boxes.xyxy
                    classes = boxes.cls
                    confidences = boxes.conf

                    for b, c, conf in zip(xyxy, classes, confidences):
                        conf_val = float(conf)
                        if conf_val < self.min_conf or conf_val > self.max_conf:
                            continue

                        cid = int(c)
                        class_name = self.model_names.get(cid, str(cid))
                        cx, cy, bw, bh = convert_to_yolo_bbox(b.tolist(), w_img, h_img)

                        yolo_annotations.append({
                            'cid': cid,
                            'class_name': class_name,
                            'cx': cx,
                            'cy': cy,
                            'w': bw,
                            'h': bh,
                            'conf': conf_val
                        })

                # Decide whether to save:
                # 1. Frames with detected instances (crucial for review & false-positive correction)
                # 2. Low-frequency background frames without detections (to prevent hallucination)
                if yolo_annotations:
                    self.save_sample(frame_1080p, yolo_annotations, production_house, area_type)
                elif random.random() < self.save_empty_ratio:
                    # Save negative background sample with empty .txt file
                    self.save_sample(frame_1080p, [], production_house, area_type)

        except Exception as e:
            print(f"Exception on {production_house}_{area_type}: {e}")
        finally:
            cap.release()


def parse_arguments():
    default_camera_file = "camera_list_v4.json"
    if not os.path.exists(default_camera_file) and not (Path(dir_path) / default_camera_file).exists():
        default_camera_file = "camera_list_v4_newplants.json"

    parser = argparse.ArgumentParser(description="Industrial PPE Dataset Collector for Retraining")
    parser.add_argument(
        "--cameras", "-c",
        type=str,
        default=default_camera_file,
        help="Path to camera list JSON file"
    )
    parser.add_argument(
        "--model", "-m",
        type=str,
        default=DEFAULT_MODEL_PATH,
        help="Path to trained YOLO weights (.pt) for pre-annotations"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="retraining_dataset",
        help="Local output directory for dataset"
    )
    parser.add_argument(
        "--s3-prefix",
        type=str,
        default="retraining_dataset",
        help="S3 folder path prefix for dataset storage"
    )
    parser.add_argument(
        "--interval", "-i",
        type=float,
        default=45.0,
        help="Sampling interval per camera in seconds (default: 45s)"
    )
    parser.add_argument(
        "--days", "-d",
        type=float,
        default=3.0,
        help="Duration to run collection in days (default: 3 days)"
    )
    parser.add_argument(
        "--hours",
        type=float,
        default=None,
        help="Duration to run collection in hours (overrides --days if provided)"
    )
    parser.add_argument(
        "--workers", "-w",
        type=int,
        default=None,
        help="Worker thread count (defaults to camera count, max 200)"
    )
    parser.add_argument(
        "--min-conf",
        type=float,
        default=0.35,
        help="Minimum confidence threshold for pre-annotations (default: 0.35)"
    )
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_arguments()

    # Determine collection duration
    total_hours = args.hours if args.hours is not None else (args.days * 24.0)
    end_time = datetime.now() + timedelta(hours=total_hours)

    print("=" * 72)
    print("       INDUSTRIAL PPE RETRAINING DATASET COLLECTOR")
    print("=" * 72)
    print(f"Target duration:      {total_hours:.1f} hours ({total_hours / 24.0:.2f} days)")
    print(f"Scheduled completion: {end_time.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Sampling interval:    Once every {args.interval}s per camera")
    print(f"Local output folder:  {args.output}")
    print(f"S3 destination:       s3://{bucket_name or '[unconfigured]'}/{args.s3_prefix}/")
    print(f"Format:               Clean raw JPEG images + standard YOLO .txt label files")
    print("=" * 72)

    # Locate camera configuration
    camera_file = args.cameras
    if not os.path.exists(camera_file):
        alt = Path(dir_path) / camera_file
        if alt.exists():
            camera_file = str(alt)
        else:
            raise FileNotFoundError(f"Camera configuration file not found at: {camera_file}")

    with open(camera_file, "r") as f:
        devices = json.load(f)

    # Initialize collector engine
    collector = DatasetCollector(
        model_path=args.model,
        output_dir=args.output,
        s3_prefix=args.s3_prefix,
        sample_interval=args.interval,
        min_conf=args.min_conf
    )

    # Extract camera tasks
    tasks = []
    for plant, plantData in devices.items():
        if not isinstance(plantData, dict): continue
        for productionHouse, phData in plantData.items():
            if not isinstance(phData, dict): continue
            for areaType, areaData in phData.items():
                if not isinstance(areaData, dict): continue
                if not areaData.get('streamLink'): continue
                ppe_list = areaData.get("ppeList", [])
                tasks.append((areaData, plant, productionHouse, areaType, ppe_list))

    total_cameras = len(tasks)
    workers = args.workers or max(16, min(200, total_cameras))
    print(f"Registered {total_cameras} camera streams. Running with {workers} worker threads.")

    with ThreadPoolExecutor(max_workers=workers) as executor:
        for areaData, plant, ph, area, ppe_list in tasks:
            executor.submit(collector.process_camera, areaData, plant, ph, area, ppe_list)

        try:
            while datetime.now() < end_time and collector.running:
                time.sleep(30)
                remaining = end_time - datetime.now()
                rem_hours = max(0.0, remaining.total_seconds() / 3600.0)
                with collector.stats_lock:
                    saved = collector.total_saved
                print(f"[STATUS] {saved} samples collected. Time remaining: {rem_hours:.1f} hours ({rem_hours/24.0:.2f} days)")

            print("\nDataset collection period complete!")
        except KeyboardInterrupt:
            print("\nStopping dataset collection gracefully...")
        finally:
            collector.running = False
            executor.shutdown(wait=False)

    print("=" * 72)
    print(f"Total samples collected: {collector.total_saved}")
    print("Class distribution in collected dataset:")
    for cname, cnt in sorted(collector.class_counts.items(), key=lambda x: -x[1]):
        print(f"  - {cname:15s}: {cnt}")
    print(f"Dataset ready at: {args.output}")
    print("=" * 72)
